### ISSUE TITLE
Openmp

### ISSUE THREAD

**Issue by daijiang** [PedroBSB/Rlda#16]
Hi @PedroBSB , I cannot build/install the package now since this error:

```
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Users/dli/R/Rcpp/include" -I"/Users/dli/R/RcppArmadillo/include" -I"/Users/dli/R/RcppProgress/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
clang: error: unsupported option '-fopenmp'
make: *** [registerDynamicSymbol.o] Error 1
ERROR: compilation failed for package ‘Rlda’
```

I think this probably is because I do not have openmp installed, right？

**Comment by PedroBSB** [comment]
Hi @daijiang . This is a strange error... Since our package was able to be compiled in all platforms (https://cran.r-project.org/web/packages/Rlda/index.html). I don't think you need the openmp... You can try the OS X Version. But I will search how to solve this as well...

**Comment by daijiang** [comment]
I did not install from CRAN, instead I am installing the github repo...

**Comment by PedroBSB** [comment]
Ok! Probably this can help us: https://github.com/Microsoft/LightGBM/issues/3

**Comment by daijiang** [comment]
I still cannot build at my machine, but it seems travis can build it (but with latex errors.)

**Comment by PedroBSB** [comment]
That is ok, @daijiang . I will looking for a solution for this.

**Comment by daijiang** [comment]
I did not figure out how to enable the `-fopenmp` option in clang. I ended with removing the `src/Makevars` file to be able to build the package. And it seems removing this file does not affect the functionality of the package...
