### ISSUE TITLE
Travis auto deploy?

### ISSUE THREAD

**Issue by daijiang** [PedroBSB/Rlda#17]
Hi @PedroBSB , do you want to set up Travis auto deployment? It will automatically test whether the package can be installed or not.

For example, in [my fork](https://github.com/daijiang/Rlda), I got this error at this moment:

```
Error: processing vignette 'Rlda.ltx' failed with diagnostics:
Running 'texi2dvi' on 'Rlda.ltx' failed.
LaTeX errors:
! LaTeX Error: File `calrsfs.sty' not found.
```

If you want, I will submit a pull request.

**Comment by PedroBSB** [comment]
Yes!! Thank you..
