### ISSUE TITLE
vignettes does not work

### ISSUE THREAD

**Issue by daijiang** [PedroBSB/Rlda#20]
I also cannot build the vignettes, since the R.rsp package is missing? What is it?

I ended up to ignore the vignettes in order to pass the check.

There are still 2 warnings (un-documented arguments; the other warning is because I removed some items in the birds.Rd, there are just too many...) and 2 notes (grey and legend global functional unavailable for plot.lda).

**Comment by PedroBSB** [comment]
Hey @daijiang !
The R.rsp is used to compile our article (which was written in Latex) in a pdf file.
This will be our vignette.
I will look those warnings!!
Thank you for helping.
