### ISSUE TITLE
vector when using summary of rlda to extract Theta and Phi

### ISSUE THREAD

**Issue by dylancraven** [PedroBSB/Rlda#21]
After fitting a bernoulli lda model, I would like to get parameter estimates using of Phi and Theta using:

summary(res, burnin=0.2, silent=TRUE)$Theta

but the output is just a null vector.

**Comment by PedroBSB** [comment]
Hi, @dylancraven you just need to specify the right object. Please, consider the following example:
```
# Presence
data(presence)
# Set seed
set.seed(9842)
# Hyperparameters for each prior distribution
gamma <- 0.01
alpha0 <- 0.01
alpha1 <- 0.01
# Execute the LDA for the Bernoulli entry
res <- rlda.bernoulli(data = presence, n_community = 10,
                      alpha0 = alpha0, alpha1 = alpha1, gamma = gamma,
                      n_gibbs = 5000,ll_prior = TRUE, display_progress = TRUE)

res.summary <-summary(res, burnin=0.2, silent=TRUE)
Theta<-res.summary$Theta.mean
```
If you have any question, please let me know.

**Comment by dylancraven** [comment]
Thank you! It would be helpful to update the code in the Example for summary.rlda
