### ISSUE TITLE
Review the article grammar.

### ISSUE THREAD

**Issue by PedroBSB** [PedroBSB/Rlda#7]
@daijiang could you look our article and look for some grammar and types errors ?
Also if you find some confuse paragraph could you help me to rewrite ?
You can find the text inside [https://github.com/PedroBSB/Rlda/blob/master/vignettes/my-vignette.Rmd](https://github.com/PedroBSB/Rlda/blob/master/vignettes/my-vignette.Rmd)
Thanks...

**Comment by daijiang** [comment]
I will do it this week. Sorry for the delay.

**Comment by PedroBSB** [comment]
[article.pdf](https://github.com/PedroBSB/Rlda/files/842398/article.pdf)
Thank you, @daijiang . This is the latest version.

**Comment by daijiang** [comment]
Hey Pedro,
I cannot find the Rmd file in Github. Can you send a copy to me?
Thanks.
Daijiang

On Mar 14, 2017, at 2:55 PM, Pedro Albuquerque <notifications@github.com<mailto:notifications@github.com>> wrote:


article.pdf<https://github.com/PedroBSB/Rlda/files/842398/article.pdf>
Thank you, @daijiang<https://github.com/daijiang> . This is the latest version.

**Comment by PedroBSB** [comment]
The  JSS asked us to write the article in their format:
[Article.zip](https://github.com/PedroBSB/Rlda/files/848351/Article.zip)
It is written in TEX.

**Comment by daijiang** [comment]
Got you. Thanks.
